-- Activities for the exercise logger, with approximate MET values based on
-- the Compendium of Physical Activities. Calories burned = MET × kg × hours.
insert into public.exercises (name, category, met) values
  ('Walking, easy (3 km/h)', 'Walking', 2.8),
  ('Walking, moderate (5 km/h)', 'Walking', 3.5),
  ('Walking, brisk (6.5 km/h)', 'Walking', 5.0),
  ('Hiking', 'Walking', 6.0),
  ('Running (8 km/h)', 'Running', 8.3),
  ('Running (10 km/h)', 'Running', 9.8),
  ('Running (12 km/h)', 'Running', 11.5),
  ('Cycling, leisurely', 'Cycling', 4.0),
  ('Cycling, moderate (19–22 km/h)', 'Cycling', 8.0),
  ('Stationary bike, moderate', 'Cycling', 6.8),
  ('Swimming laps, moderate', 'Swimming', 5.8),
  ('Swimming laps, vigorous', 'Swimming', 9.8),
  ('Weight training, general', 'Strength', 3.5),
  ('Weight training, vigorous', 'Strength', 6.0),
  ('Circuit training / HIIT', 'Strength', 8.0),
  ('Rowing machine, moderate', 'Cardio machines', 7.0),
  ('Elliptical, moderate', 'Cardio machines', 5.0),
  ('Stair climber', 'Cardio machines', 9.0),
  ('Jump rope', 'Cardio machines', 11.8),
  ('Yoga', 'Mind & body', 2.5),
  ('Pilates', 'Mind & body', 3.0),
  ('Dancing', 'Sports', 5.0),
  ('Football (soccer), casual', 'Sports', 7.0),
  ('Basketball, game', 'Sports', 6.5),
  ('Tennis, singles', 'Sports', 8.0),
  ('Badminton, casual', 'Sports', 5.5),
  ('Cricket', 'Sports', 4.8),
  ('Housework, general', 'Everyday', 3.3),
  ('Gardening', 'Everyday', 3.8);
